blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogpost.urls')),
]

blogpost/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'blog'


urlpatterns = [


    path('',views.index,name ="index"),

    path('register/',views.register,name="register"),

    path('login/',views.login,name="login"),

    path("logout/", views.logout_request, name="logout"),

    path('home/search', views.search_filter,name = "search"),

    path('home/search-exact', views.search_filter_exact,name = "xyz"),

    path('home/<int:author_id>/', views.user_profile, name = "profile"),

    path('home/tag/<int:id>/',views.tag_profile,name="tagprofile"),

    path('home/',PostListView.as_view(),name="home"),

    path('<slug:slug>/',PostDetailView.as_view(),name="post-detail"),

    path('home/new/', PostCreateView.as_view(),name="post-create"),

    path('<slug:slug>/update',PostUpdateView.as_view(),name="post-update"),

    path('<slug:slug>/delete',PostDeleteView.as_view(),name="post-delete"),



]   

blogpost/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save, pre_save
from django.template.defaultfilters import slugify

# Create your models here.
class Tag(models.Model):
	category_type = models.CharField(max_length = 100)

	def __str__(self):
		return self.category_type


class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	tag = models.ManyToManyField(Tag)
	slug =models.SlugField(null=False, unique=True, blank =True )

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post-detail', kwargs={'slug': self.slug})

	# def save(self, *args, **kwargs):
	# 	if not self.slug:
	# 		self.slug = create_slug(self.title)
	# 	return super(Post, self).save(*args, **kwargs)
		
def new_slug(instance, new_slug=None, **kwargs):

	# import pdb; pdb.set_trace()
	slug = slugify(instance.title)
	class_exist = Post.objects.filter(slug = slug).exists()
	# latest_pk = 1
	if class_exist:
		latest_pk = Post.objects.latest('pk').id
		latest_pk +=1

		slug = "{}-{}".format(slug, latest_pk)
	
	instance.slug = slug

pre_save.connect(new_slug, sender = Post)

#(not working)-
# def udpate_slug(sender,**kwargs):
# 	if kwargs['created']:
# 		updateslug =Post.objects.update(slug = kwargs['instance'])

# post_save.connect(udpate_slug, sender = Post)

class UserProfile(models.Model):
	author = models.OneToOneField(User,on_delete=models.CASCADE)
	
	def __str__(self):
		return self.author.username

def CreateProfile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(author=kwargs['instance'])

post_save.connect(CreateProfile, sender = User)

# @receiver(post_save, sender=User)    -- USING THE @receiver decorators
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
# #         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete =models.CASCADE)
	author = models.ForeignKey(User,on_delete = models.CASCADE)
	Pub_date = models.DateTimeField(default =timezone.now)
	contex = models.TextField()

	def __str__(self):
		return self.contex

class Text(models.Model):
	content = models.TextField()

	def __str__(self):
		return self.content

def postalert(sender,instance,**kwargs):
	alert = Text.objects.create(content='New post created {}'.format(instance.title))

post_save.connect(postalert, sender = Post)



# If you want to register the receiver function to several signals you may do it like this:
# @receiver([post_save, post_delete], sender=User)

blogpost/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserCreateForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

	# def __init__(self, *args, **kwargs):
	# 	super(UserCreateForm, self).__init__(*args, **kwargs)

	# 	for fieldname in ['username', 'password1', 'password2','first_name', 'last_name', 'email']:
	# 		self.fields[fieldname].help_text = None
		

	def clean_username(self):
		user = self.cleaned_data.get('username')
		try:
			match = User.objects.get(username =user)
		except:
			return user
		raise forms.ValidationError("Username alredy exists!!!")
		if not '@' in user or '#' in user or '!' in user:
			raise forms.ValidationError("Usernames should have special characters.")
		return user


# class PostCreateForm(forms):
# 	title = forms.CharField(max_length=30, required=True)
# 	content = forms.TextField()

# 	class Meta:
# 		model = User
# 		fields = ('title','content')

blogpost/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login as auth_login
from django.http import HttpResponse
from django.contrib.auth.models import User
from .filters import TitleFilter
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import Post,Comment,Tag,UserProfile
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from blogpost.forms import UserCreateForm
from django.contrib import messages 
from django.views.generic import ListView,DetailView, CreateView, UpdateView, DeleteView
# Create your views here.

def index(request):
	return render(request,'blog/index.html')

def register(request):

    if request.method == 'POST':
        #import pdb;pdb.set_trace()
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            messages.success(request, "user registration succesfull")
            # login(request)
            return redirect('blog:home')
        else:
            print(form.errors)      
            return render(request,'blog/register.html',{'form' : form})
    else:            
        form = UserCreateForm()
        return render(request,'blog/register.html',{'form' : form})
        
def login(request):
    
    #import pdb;pdb.set_trace()
    if request.method == 'POST':
        form = AuthenticationForm(request,request.POST)
       
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            messages.success(request,"Welcome {}".format(username))
            return redirect("blog:home")
            
        else:
            messages.error(request,"Invalid username or password")
            return render(request,'blog/login.html',{'form' : form})
    else:
        form =AuthenticationForm()
        return render(request,'blog/login.html',{'form' : form})
	

def logout_request(request):
    logout(request)
    messages.info(request,"succesfully Logged OUT !!!!!!!")
    return redirect("blog:index")

def home(request):
    post = Post.objects.order_by('-date_posted')
    return render(request,'blog/home.html',{'Post':post})

def user_profile(request,author_id):
    #import pdb;pdb.set_trace()
    author = User.objects.get(id = author_id)
    post = Post.objects.filter(author__id = author_id )
    return render(request, 'blog/user_profile.html',{'Post':post, 'author':author})

def tag_profile(request,id):

    #import pdb;pdb.set_trace()
    instance = get_object_or_404(Tag, id=id)
    #tag = Tag.objects.get(id = tag_id)
    ins = instance.post_set.all()
    context = {"instance": ins}
    return render(request,'blog/tag_profile.html',context)


def search_filter(request):

    search = Post.objects.all()
    # import pdb;pdb.set_trace()
    title_contains_query = request.POST.get('title_contains')

    if title_contains_query != " " and title_contains_query is not None:
        search = search.filter(title__contains = title_contains_query)

    return render(request,'blog/search.html',{'Search':search, 'title':'Search by contains filter'})


def search_filter_exact(request):
    # import pdb;pdb.set_trace()
    search = Post.objects.all()
    import pdb;pdb.set_trace()
    title_contains_query = request.POST.get('title_contains')

    if title_contains_query != " " and title_contains_query is not None:
        search = search.filter(title__iexact = title_contains_query)

    return render(request,'blog/search.html',{'Search':search, 'title':'Search by exact filter'})
    #search = Post.objects.filter(title__contains = 'g')
    # search = Post.objects.all()
    # title_contains_query = request.GET.get('title_contains')
    # author_contains_query = request.GET.get('author_contains')
    # tag_contains_query = request.GET.get('tag_contains')

    # if title_contains_query != " " and title_contains_query is not None:
    #     search = search.filter(title__icontains = title_contains_query)


class PostListView(ListView):
    model = Post
    template_name ="blog/home.html"  #<app>/<model>_<viewtype>.html
    context_object_name = "Post"
    ordering = ['-date_posted']   # as compared to (post = Post.objects.order_by('-date_posted')) in function view

class PostDetailView(DetailView):
    model = Post
    template_name ="blog/post_detail.html"  #<app>/<model>_<viewtype>.html
    context_object_name = "post"

class PostCreateView(CreateView):
    model = Post
    fields = ["title","content","tag"]
    template_name ="blog/post_form.html"

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title","content"]
    template_name ="blog/post_form.html"

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # def test_funct(self):
    #     Post = self.get_object()
    #     if self.request.user == Post.author:
    #         return True
    #     return False



class PostDeleteView(DeleteView):
    model = Post
    success_url = '/home'
    template_name ="blog/post_confirm_delete.html"

blogpost/templates/blog/home.html
<!DOCTYPE html>
<html>
<head>

	<title>Home</title>

</head>
<style>
	
	*{
		background-color: #323a3d;
		padding: 0px;
		margin: 0px;

	}

	h1{
		margin-top: 15px;
	}
</style>
	<body>

	{% if request.user %}
		
		<h1 style="color:#ff008c; margin: 10px">{{request.user.username}}</h1>
	
	{% endif %}
		
		{% if messages %}

						    <ul class="messages"> 
						    	{% for message in messages %}	
						    	
						    		<li>
						    			<div style="color: red" class="alert alert-success">{{ message }}</div>
						    		</li>

						    	{% endfor %}
						    </ul>
	    
						{% endif %}


						<!-- <form method="GET">
						    {{ form.title }}
						    <button type="submit">Search</button>
						</form> -->

						 <div style="margin-left: 1000px" class="Search">
							
													
							<button style=" background-color: white;padding: 5px"><a  style="background-color: white; padding: 5px; color: green;" href="{% url 'blog:search' %}">Search with the title</a></button>

							

						</div>	 



		<div>
			<span>				
				<center><h1 style="font-style: italic; color: darkorange">Welcome to home page</h1></center>


				<ul style="text-align: right; margin-right: 50px;">

					<li style="display: inline-block;font-size: 18px; padding: 10px; margin: 5px "><a style="color: #ff008c " href="{% url 'blog:post-create' %}"> Create New Post</a></li>
					<li style="display: inline-block;font-size: 18px; padding: 10px; "><a style="color: white" href="{% url 'blog:logout' %}">Logout</a></li>



				</ul>
		</div>	</span>

		<div style="margin: 10px;margin-top: 30px;padding: 5px ">
		<span>
				{% for post in Post %}
						<h2 style="color: #d1c690"><a style="color: #d1c690" href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></h2>

						<div class="form-group">

							{% if request.user == post.author %}

								<button style="margin-left: 700px; padding: 10px;  color: white; background-color:green"><a style="padding: 10px;  color: white; background-color:green" href="{% url 'blog:post-update' post.slug %}">Update</a></button>
								
								<br><br>

								<button style="margin-left: 700px; padding: 10px;  color: white; background-color:red"><a style="padding: 10px;  color: white; background-color:red" href="{% url 'blog:post-delete' post.slug %}">Delete</a></button>

							{% endif %}
						</div>
							<p style="color: #d1c690">By <a style="color: #ff008c " href="{% url 'blog:profile' post.author_id %}">{{ post.author }}</a> on {{ post.date_posted }}</p>
						
					
						<br><br>

				{% endfor %}
		</span>
		</div>		

		

	</body>
</html>

blogpost/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Index page</title>

	<link rel="stylesheet" type="text/css" href="{% static 'blogpost/style.css' %}">

	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>


<div>
<!-- 	 <nav class="navbar navbar-inverse">
 -->	<div class="container-fluid" style="background-color: #000000">
		    
		    <div>
		      <a class="navbar-brand" href="#" style="color: orange; font-size: 25px">BLOGAPP</a>
		    </div>
		    
		    <ul class="nav navbar-nav navbar-right" style="font-size: 16px;margin-right: 15px;">
		      <li><a style="color: orange" href="{% url 'blog:register'%}">Register</a></li>
		      <li><a style="color: orange" href="{% url 'blog:login'%}">Login</a></li>
		    </ul>

	 	</div>

	</nav> 
</div>		

<!--   <div class="jumbotron" style="margin-top: 30px;margin: 20px;">
    <h1 style="margin-left: 15px;">Welcome</h1>      
    <p style="margin-left: 20px";>Login / Register to view the blog content</p>
  </div> -->


<!-- <h1 class="head">
	images
</h1>
 -->

<!-- <div>
	
	<img src="{% static 'blogpost/images/ny.jpg' %}" style="height: 500px;">

</div>
 -->


<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="{% static 'blogpost/images/1.png' %}" alt="Los Angeles">
    </div>

    <div class="item">
      <img src="{% static 'blogpost/images/2.jpg' %}" alt="Chicago">
    </div>

    <div class="item">
      <img src="{% static 'blogpost/images/3.jpg' %}" alt="New York">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>	


</body>
</html>

blogpost/templates/blog/login.html
<!DOCTYPE html>
<html>
<head>
	<title>login</title>

	
</head>
<body>

	

	{% block body %}

	  <h2>Login</h2>

	  <form method="post">
	  
	    {% csrf_token %}

	    {% if messages %}

					    <ul class="messages"> 
					    	{% for message in messages %}	
					    	
					    		<li>
					    			<div class="alert alert-success">{{ message }}</div>
					    		</li>

					    	{% endfor %}
					    </ul>
    
					{% endif %}

	    {{ form.as_p }}

	    	
	  
	    <button type="submit">Login</button>
	  
	  </form>
	  
	{% endblock %}

</body>
</html>

blogpost/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
	<title>New Post </title>
</head>
<body>

		<center><h2>Delete Post</h2></center>
	
	<div style="margin-left: 100px; margin-top: 50px">

	<form method="POST">

	{% csrf_token %}
	
	<div style="margin: 15px;">

		<h2>Are you sure you want to delete the post - {{ object.title }}? </h2>

		<button style="margin-left: 100px; color: white; background-color: red;padding: 5px  " type="submit">Yes,Delete</button>

		<button style="margin-left: 100px; color: white; background-color: green;padding: 5px " type="submit"><a href="{% url 'blog:post-detail' object.slug %}">Cancel</a></button> 	

	</div>		
		
	</div>
</body>
</html>
 

blogpost/templates/blog/post_detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<style>
	
	*{background-color: #323a3d;

	}
</style>
	<body>
		<div style="margin: 10px;margin-top: 30px;padding: 5px ">

						<h2 style="color: #d1c690">{{ post.title }}</h2>
						<p style="color: #d1c690">By {{ post.author }} on {{ post.date_posted }}</p>
					{% for t in post.tag.all %}
						<p style="color: #c8dbab"> Tags:
						{{ t.category_type}}
						</p>
					{% endfor %}
						<p style="color: #e6e8da">{{ post.content | linebreaksbr }}</p>

		</div>		


	</body>
</html>

blogpost/templates/blog/post_form.html
<!DOCTYPE html>
<html>
<head>
	<title>New Post </title>
</head>
<body>

		<center><h2>Create a new post</h2></center>
	
	<div style="margin-left: 100px; margin-top: 50px">

	<form method="POST">

	{% csrf_token %}
	
	<div style="margin: 15px;">

		<label>Title</label>
		<p>{{form.title}}</p>


		<label>Content</label>
		<p>{{form.content}}</p>

		<label>Tag</label>
		<p>{{form.tag}}</p>


		<p><button style="margin-left: 100px" type="submit">Post</button> </p>
			
	</div>		
		
	</div>
</body>
</html>

<!-- <label>Title</label>	
		<input style="width: 400px; margin-left: 70px" type="text" placeholder="Enter Title">

		<br><br>
		
		<label>Content</label>
		<input style=" height: 300px; width: 400px; top: 10px; margin-left: 43px" placeholder="Write the Post content">

		<br><br>

		<button style="margin-left: 300px" type="submit">Post</button>
 -->

blogpost/templates/blog/register.html
<!DOCTYPE html>
<html>
	<head>
			<title>Register</title>
	</head>

	<body>
		{% block content %}

			  <center><h2>Sign up</h2></center>

			  <form method="post">

				    {% csrf_token %}
				
		<div id="form" style="margin-left: 80px">	
				<div id ="username">
					
					<label>Username</label>

					
					{{form.username}}

					<p>{{ form.username.errors }}</p>
		
				 </div>
		  
				
				<div id ="fstname">
					
					<label>First Name</label>

					{{form.first_name}}
					
				 </div>

			<br>
				
				<div id ="lstname">
					
					<label>Last Name</label>

					{{form.last_name}}

				 </div>
		 <br>
				
				<div id ="email">
					
					<label>Email ID </label>

					{{form.email}}
					
					<p>{{form.email.errors}}</p>

				 </div>
			
		
				
				<div id ="password1">
					
					<label>Password</label>

					{{form.password1}}
					
					<p>{{form.password2.errors}}</p>
					
				 </div>


				 
				<div id ="password2" style="padding: 5px">
					
					<label>Confirm Password</label>

					{{form.password2}}
					
					<p>{{form.password2.errors}}</p>


				 </div>
	  	
				    
			</div>	    

				    <button style="margin-left: 100px" type="submit">Register</button>

			  </form>

		{% endblock %}

	</body>
</html>

blogpost/templates/blog/search.html
<!DOCTYPE html>
<html>
<head>
	<title>Search</title>

	<style>
	
	*{
		background-color: #323a3d;
		padding: 0px;
		margin: 0px;

	}

	h1{
		margin-top: 15px;
	}
	h2 {
		color: pink;
		margin:10px;
	}
</style>
</head>
<body>

	<h2>{{title}}</h2>

	<div style="margin-top: 20px" class="Search">

	

	<center><form method="POST" 
	action="{% if title == 'Search by contains filter' %}
		{% url 'blog:search' %}
		{% else %}
		{% url 'blog:xyz' %}
		{% endif %}
		">
	{% csrf_token %}
							
		<input name="title_contains"  style="color: red; background-color: white; padding: 8px;" type="text" placeholder="Search..">


							
		<button style="background-color: white;padding: 5px;" type="submit">Search</button></center>

	</form>
							
 
	</div>			

	<div style="margin-top: 80px; color: #d1c690">		

		


		
				{% for search in Search %}

				
					<p style="color: #c8dbab;"><a style="color: #d1c690" href="{% url 'blog:post-detail' search.slug %}">{{ search }}</a>

					{% for t in search.tag.all %} 

					<center><a style="color: #d1c690" href="{% url 'blog:tagprofile' t.id %}"> Tags : {{ t.category_type}}</a></center>

					{% endfor %}</p>

					<hr>
					
				{% endfor %}	
	</div>


</body>
</html>

blogpost/templates/blog/tag_profile.html
<!DOCTYPE html>
<html>
<head>
	<title>Tag</title>

	<style>
	
	*{
		background-color: #323a3d;
		padding: 0px;
		margin: 0px;

	}

	h1{
		margin-top: 15px;
	}
</style>
</head>
<body>	


		{% for i in instance %}
			<br>
  			<a style="color: #d1c690" href="{% url 'blog:post-detail' i.slug %}">{{ i.title }}</a>
  			<!-- {{ i.content }} --><hr>
		{% endfor %}

</body>
</html>

blogpost/templates/blog/user_profile.html
<!DOCTYPE html>
<html>
<head>
	<title>User Profile</title>

	<style>
	
	*{
		background-color: #323a3d;
		padding: 0px;
		margin: 0px;

	}

	h1{
		margin-top: 10px;
	}

	h2{
		margin: 30px;
	}
</style>
</head>
<body>
		<div>

				<h1 style="color:#ff008c; margin: 10px">{{ author }}</h1>

		{% for post in Post %}
		
				<h2 style="color: #d1c690;"><a style="color: #d1c690" href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></h2>
			
			    
	    {% endfor %}


		</div>
</body>
</html>